### ISSUE TITLE
Instant Splat Comparison

### ISSUE THREAD

**Issue by pablovela5620** [hanyangyu1021/LMGaussian#2]
Congrats on the release! I was reading through the paper and wanted to ask if there was any benchmarking against [InstantSplat](https://instantsplat.github.io/)? Seems like the two methods are very similar in their initializations. Thanks!

**Comment by hanyangyu1021** [comment]
Thank you for your interest in our research! You are correct in noting that both our project and Instantsplat leverage the powerful prior DUSt3R for initialization. However, our respective focuses diverge in terms of methodology. Instantsplat employs down-sampling techniques to expedite training, while our work emphasizes operations such as point cloud cleaning and depth regularization to enhance the quality of the point cloud. Furthermore, rather than relying solely on Gaussian splatting post-initialization, our approach integrates strategies like regularization and diffusion repair. For a comprehensive comparison, feel free to utilize the data provided in the ./data/horse16 directory and evaluate it using Instantsplat.

**Comment by pablovela5620** [comment]
great, thanks
