### ISSUE TITLE
slow training speed

### ISSUE THREAD

**Issue by yt0409** [hanyangyu1021/LMGaussian#5]
thank you for your great work, i meet a question while training.the speed is much slower than 3dgs，can you please tell me some possible reasons? very thanks
![Snipaste_2024-10-12_21-45-27](https://github.com/user-attachments/assets/79998daa-0849-4288-98fb-5ab0fa0dbae8)

**Comment by hanyangyu1021** [comment]
Thanks for your attention, the speed limit may lie in the regularization constraint. In the algorithm, in order to prevent network overfitting, we add several regularization constraints, such as local_pearson regularization, which turns a image into small patches, and calculates loss for each patch, which will increase the speed of network training. You can try increasing the size of the patch in local_pearson_loss in stage1_360 line 282 or simply removing this local loss~
